version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - gosec
    - unconvert
    - goconst
    - misspell
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives

formatters:
  enable:
    - gofmt
    - goimports
